name: Reusable Terraform Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      action:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # - name: Configure AWS Credentials (OIDC)
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: arn:aws:iam::ACCOUNT-ID:role/ROLE-NAME
      #     aws-region: us-east-1

      - name: Terraform Init (skip backend)
        run: terraform init -backend=false
        working-directory: environments/${{ inputs.environment }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: environments/${{ inputs.environment }}

        # ---- TFLINT ----
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3

      - name: Run TFLint
        run: tflint --init && tflint
        working-directory: environments/${{ inputs.environment }}

      - name: Run Trivy IaC Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'config'
          scan-ref: '.'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'

      - name: Terraform Plan
        if: inputs.action == 'plan'
        run: terraform plan
        working-directory: environments/${{ inputs.environment }}

      # - name: Terraform Apply
      #   if: inputs.action == 'apply' && github.ref == 'refs/heads/main'
      #   run: terraform apply -auto-approve
      #   working-directory: environments/${{ inputs.environment }}

      - name: Terraform Destroy
        if: inputs.action == 'destroy'
        run: terraform destroy -auto-approve
        working-directory: environments/${{ inputs.environment }}

