name: Terraform Apply Prod

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  apply-prod:
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      environment: prod
      action: apply
    secrets:
      inherit