name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  call-reusable:
    environment: production
    uses: ../.github/workflows/reusable-terraform.yml
    with:
      environment: prod
      action: apply
