name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  plan-dev:
    uses: ./reusable-terraform.yml
    with:
      environment: dev
      action: plan
    secrets:
      inherit
