name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  plan-dev:
    uses: omarionay/aws-terraform-cicd-github/.github/workflows/reusable-terraform.yml
    with:
      environment: dev
      action: plan
    secrets:
      inherit
