name: Terraform Plan

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  plan-dev:
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      environment: dev
      action: plan
    secrets:
      inherit
