name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  call-reusable:
    uses: ./.github/workflowsreusable-terraform.yml
    with:
      environment: prod
      action: apply
    secrets: inherit